apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik-acme-pv
  namespace: traefik
spec:
  capacity:
    storage: 10Gi 
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ebs-sc
  awsElasticBlockStore:
    volumeID: "vol-0ec3977019d6acc45"
    fsType: ext4
