apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "classic"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: web
      protocol: TCP
      name: http
    - port: 443
      targetPort: websecure
      protocol: TCP
      name: https
  selector:
    app: traefik

