---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: images-cert
  namespace: apps
spec:
  commonName: demo-images.anup.co.in
  secretName: images-cert
  dnsNames:
    - "demo-images.anup.co.in"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: video-cert
  namespace: apps
spec:
  commonName: demo-video.anup.co.in
  secretName: video-cert
  dnsNames:
    - "demo-video.anup.co.in"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demo-cert
  namespace: apps
spec:
  commonName: demo-audio.anup.co.in
  secretName: demo-cert
  dnsNames:
    - "demo-audio.anup.co.in"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
