---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: images-cert
  namespace: apps
spec:
  commonName: images.anup.co.in
  secretName: images-cert
  dnsNames:
    - "images.anup.co.in"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: video-cert
  namespace: apps
spec:
  commonName: video.anup.co.in
  secretName: video-cert
  dnsNames:
    - "video.anup.co.in"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demo-cert
  namespace: apps
spec:
  commonName: demo.anup.co.in
  secretName: demo-cert
  dnsNames:
    - "demo.anup.co.in"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
