apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traefik-secrets-access-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: traefik
roleRef:
  kind: ClusterRole
  name: traefik-secrets-access
  apiGroup: rbac.authorization.k8s.io
